import keyMirror from 'key-mirror';

export default keyMirror({
  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  REGISTER_REQUEST: null,
  REGISTER_SUCCESS: null,
  REGISTER_FAILURE: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  USERNAME_TEXT_CHANGE: null,
  PASSWORD_TEXT_CHANGE: null,
  CONFIRM_PASSWORD_TEXT_CHANGE: null,

  GET_EVENTS_REQUEST: null,
  GET_EVENTS_SUCCESS: null,
  GET_EVENTS_FAILURE: null,

  ADD_EVENT_REQUEST: null,
  ADD_EVENT_SUCCESS: null,
  ADD_EVENT_FAILURE: null,

  ADD_LIKE_REQUEST: null,
  ADD_LIKE_SUCCESS: null,
  ADD_LIKE_FAILURE: null,

  ADD_COMMENT_REQUEST: null,
  ADD_COMMENT_SUCCESS: null,
  ADD_COMMENT_FAILURE: null,

  GET_LIKES_REQUEST: null,
  GET_LIKES_SUCCESS: null,
  GET_LIKES_FAILURE: null,

  GET_COMMENTS_REQUEST: null,
  GET_COMMENTS_SUCCESS: null,
  GET_COMMENTS_FAILURE: null,
});
